Repository nephio-project/catalog, pull requests merged in 2025-06, with the labels that each got.

#115 Fix gitea init setup
  distros/sandbox/gitea/secret-gitea.yaml
Labels: bug, approved

#116 Fix gitea config for 1.23.8
  distros/sandbox/gitea/secret-gitea-init.yaml
  distros/sandbox/gitea/secret-gitea.yaml
  distros/sandbox/gitea/statefulset-gitea.yaml
Labels: bug, approved, lgtm

#122 Add ArgoCD Full Install Package
  nephio/optional/argo-cd-full/Kptfile
  nephio/optional/argo-cd-full/README.md
  nephio/optional/argo-cd-full/argo-application-crd.yaml
  nephio/optional/argo-cd-full/argo-applicationset-crd.yaml
  nephio/optional/argo-cd-full/argo-appproject-crd.yaml
  nephio/optional/argo-cd-full/argo-clusterrole.yaml
  nephio/optional/argo-cd-full/argo-clusterrolebinding.yaml
  nephio/optional/argo-cd-full/argo-cm.yaml
  nephio/optional/argo-cd-full/argo-deployment.yaml
  nephio/optional/argo-cd-full/argo-networkpolicy.yaml
  nephio/optional/argo-cd-full/argo-ns.yaml
  nephio/optional/argo-cd-full/argo-role.yaml
  nephio/optional/argo-cd-full/argo-rolebinding.yaml
  nephio/optional/argo-cd-full/argo-sa.yaml
  nephio/optional/argo-cd-full/argo-secret.yaml
  nephio/optional/argo-cd-full/argo-service.yaml
  nephio/optional/argo-cd-full/argo-statefulset.yaml
  nephio/optional/argo-cd-full/package-context.yaml
Labels: approved, lgtm
